---
title: "Reproducible Research Course Project 1"
author: "Brian Lackey"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Loading and pre-processing data

```{r}
table <- read.csv("activity.csv")
summary(table)
```

##Mean total number of steps per day
```{r}
table2<-aggregate(table$steps,list(date=table$date),FUN="sum", na.rm=TRUE)

hist(table2$x,breaks=25, main="Total Steps Taken per Day", xlab="Total Number of Steps", ylab="Days")

mean(table2$x)
median(table2$x)
```
##Average daily activity pattern
```{r}
table3<-aggregate(table$steps,list(interval=table$interval),FUN="mean", na.rm=TRUE)

plot(table3$x,type="l", main="Average number of steps per 5-minute period", ylab="Average number of steps", xlab="5-minute period")

table3[table3$x==max(table3$x),"interval"]
```
##Imputing missing values
```{r}
sum(is.na(table$steps))
#Replacing all NAs with the average for that interval
avgs<-aggregate(table$steps,list(interval=table$interval),FUN="mean",na.rm=TRUE)

table4<-merge(table,avgs,by="interval")
table4$steps<-ifelse(is.na(table4$steps),table4$x,table4$steps)

table5<-aggregate(table4$steps,list(date=table4$date),FUN="sum", na.rm=TRUE)

hist(table5$x,breaks=25, main="Total Steps Taken per Day", xlab="Total Number of Steps", ylab="Days")

mean(table5$x)
median(table5$x)
```
##Weekdays vs Weekends
```{r}
table4$day<-weekdays(as.Date(table4$date))

table4$weekvsweekend<-ifelse(table4$day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"),"Weekday","Weekend")

table6<-aggregate(table4$steps,list(interval=table4$interval, weekvsweekend=table4$weekvsweekend),FUN="mean", na.rm=TRUE)

par(mfrow=c(1,2))

plot(table6$x[table6$weekvsweekend=="Weekend"],type="l",main="Weekend",ylab="Average number of steps",xlab="5-minute period",col=1)

plot(table6$x[table6$weekvsweekend=="Weekday"],type="l",main="Weekday",ylab="Average number of steps",xlab="5-minute period",col=1)
```